name: Build and push docker image 


on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout out the repository
      uses: actions/checkout@v2

    - name: Docker Build
      run: |
        hostnamectl

  build-and-push2:
    runs-on: ubuntu-latest
    need: build-and-push1

    steps:
    - name: Checkout out the repository
      uses: actions/checkout@v2

    - name: Docker Build
      run: |
        hostnamectl


  build-and-push3:
    runs-on: ubuntu-latest
    need: build-and-push2

    steps:
    - name: Checkout out the repository
      uses: actions/checkout@v2

    - name: Docker Build
      run: |
        hostnamectl



      # uses: docker/setup-buildx-action@v3

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: your-dockerhub-username/your-image-name:latest